apiVersion: v2
name: postsrsd
description: A Helm chart for Kubernetes
type: application
version: 1.0.2
appVersion: "1.0.2"
dependencies:
- name: valkey
  version: 0.7.7
  repository: https://valkey.io/valkey-helm/
  condition: valkey.enabled
