apiVersion: v1
kind: Service
metadata:
  name: {{ include "postsrsd.fullname" . }}
  labels:
    {{- include "postsrsd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.socket.port }}
      protocol: TCP
      name: postsrsd-socket
    - port: {{ .Values.service.milter.port }}
      protocol: TCP
      name: postsrsd-ocket
  selector:
    {{- include "postsrsd.selectorLabels" . | nindent 4 }}
